version: "3"
services:
  mg_mservice_auth:
    build: .
    ports:
      - "3000:3000"
    links:
      - redis
      - mongodb
    depends_on:
      - mongodb
      - redis
    volumes:
      - ${PWD}:/home/node/app
    environment:
      NODE_ENV: "production"
      PORT: 3000
  redis:
    image: "redis:alpine"
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
